#!/bin/bash
intHDD=$( lsblk|grep SWAP|cut -c 7,8,9 )
while ! [[ $choice =~ ^sd[a-z]$ ]]
do
	clear
	echo 'Secure Erase for SATA HDDs and SSDs'
	echo ''
	lsblk|grep -v $intHDD|grep -v sr0
	echo ''
	read -p 'Please Enter a device choice from the above list (sdb, sdc, sdd etc.): ' choice
	echo ''
done
if [[ $choice = $intHDD ]]
then
	echo 'You have chosen the internal HDD. Aborting...'
	exit 1
elif [[ $( lsblk|grep $choice ) = '' ]]
then
	echo "No block device '$choice' found.  Aborting..."
	exit 1
else
	if [[ $(( hdparm -I /dev/$choice|grep SG_IO ) 2>&1 ) != '' ]]
	then
		echo "Device doesn't appear to support SATA commands.  Is it a USB?  Aborting..."
		exit 1
	else
		if [[ $( hdparm -I /dev/$choice|grep frozen|cut -f 2 ) = 'not' ]]
		then
			hdparm --user-master u --security-set-pass Wipe /dev/$choice > /dev/null #2>&1
			echo 'Issuing SECURITY ERASE command.  It should take '
			hdparm -I /dev/$choice|grep SECURITY
			hdparm --user-master u --security-erase Wipe /dev/$choice > /dev/null #2>&1
			echo ''
			echo 'All done!'
		else
			echo 'Drive is frozen.'
			echo 'Try quickly disconnecting and reconnecting the power to the drive.'
			echo 'Aborting...'
		fi
	fi
fi
