#!/bin/bash
intHDD=$( lsblk|grep SWAP|cut -c 7,8,9 )
while ! [[ $choice =~ ^sd[a-z]$ ]]
do
	clear
	echo 'Wipe USBs, HDDs or SSDs by overwriting every sector with 0x00s'
	echo ''
	lsblk|grep -v $intHDD|grep -v sr0
	echo ''
	read -p 'Please Enter a device choice from the above list (sdb, sdc, sdd etc.): ' choice
done
if [[ $choice = $intHDD ]]
then
	echo ''
	echo 'You have chosen the internal HDD. Aborting...'
	exit 1
elif [[ $( lsblk|grep $choice ) = '' ]]
then
	echo ''
	echo "No block device '$choice' found.  Aborting..."
	exit 1
else
	dc3dd wipe=/dev/$choice	
fi
while ! [[ $verify =~ ^[yYnN]$ ]]
do
	echo ''
	read -p "Do you wish to verify $choice has been wiped? (y/n): " verify
done
echo ''
if [[ $verify =~ ^[nN]$ ]]
then
	echo 'Not verifying...'
	exit 0
else
	verified=$(pv /dev/$choice|cmp - /dev/zero 2>&1|grep -v EOF|cut -f 4,5 -d ' '|cut -d ',' -f 1 )
	echo ''
	if [[ $verified = '' ]]
	then
		echo "$choice has been completely wiped..."
	else
		echo "$choice has not wiped correctly, $verified is not 0x00!"
		exit 1
	fi
fi
